### ISSUE TITLE
tagomoris will step down from the maintainer

### ISSUE THREAD

**Issue by tagomoris** [fluent/fluent-logger-golang#100]
The maintenance of this repository is now far from my current job, and on the other hand, there are many requests/demands for updating/maintaining this library (mainly for the docker logging driver).

I will not be able to work on maintaining this library as a high-priority task in the future, so I think it's time for me to step down from the maintainer.

The problem is, how we can choose the next maintainer.
Do you have any idea, guys? Or are there any volunteers?
Cc: @fluent/admins 

(Even without any replies, I'll stop working on this at the end of this year - I'll be too busy to respond to issues/pull-requests on this repo.)

**Comment by fujimotos** [comment]
@tagomoris I discussed a bit about this internally at ClearCode, and I believe we can
take over the project maintainership.

CC: @ashie @kenhys 

Thank you for your great work over such a long time.
