### ISSUE TITLE
Release v1.8.0

### ISSUE THREAD

**Issue by fujimotos** [fluent/fluent-logger-golang#108]
This ticket tracks the release of a new version of fluent-logger-golang.

 * I'm planning to make a new release as `v1.8.0`.
 * Mostly because #105 changed the behaviour of `Close()` (so not fully compatible with v1.7.0).

### Release steps

* [x] Add documentation for `FluentNewtork=tls`
* [x] Add documentation for `TlsInsecureSkipVerify={true,false}`
* [x] Document the new API behavior  introduced by #105
* [x] Add the `v1.8.0` tag to the master HEAD.
* [x] Push the tag to fluent-logger-golang

**Comment by fujimotos** [comment]
I'm planning to make a release next week (probably Monday). 

@tagomoris  Do the release steps (posted above) look good to you?
This is my first release of a go module, so I want to do it safe..

**Comment by tagomoris** [comment]
@fujimotos LGTM

**Comment by fujimotos** [comment]
@tagomoris Thank you!

**Comment by fujimotos** [comment]
I added the required documentation in #109.

**Comment by fujimotos** [comment]
v1.8.0 is oficially out!

* https://github.com/fluent/fluent-logger-golang/blob/master/CHANGELOG.md
* https://github.com/fluent/fluent-logger-golang/releases/tag/v1.8.0

Now let's close this ticket now.
