### ISSUE TITLE
Feature: periodically reconnect to fluentd-address

### ISSUE THREAD

**Issue by conorevans** [fluent/fluent-logger-golang#110]
In cases where the FluentHost can resolve to one of many IPs (e.g. a Consul service address), periodic reconnection is a desirable feature. In a Consul example, a member can be marked unhealthy and leave the service pool, or new members can be added to the service pool. While `ForceStopAsyncSend` is welcomed in that it prevents Docker containers hanging, but it doesn't prevent log loss, and a single application with a log spike can still overwhelm a fluentd worker. If periodic reconnection were in place, FluentHost could resolve to a new address and continue logging.

**Comment by fujimotos** [comment]
Resolved by #111 (merged via 1c05506788e99e7338ead5b555a0b6268061a023)
