### ISSUE TITLE
can't convert to msgpack

### ISSUE THREAD

**Issue by fujiwara** [fluent/fluent-logger-golang#12]
I've found an incompatible issue between v0.5.1 and v0.6.0.

```
$ go test -bench Benchmark_PostWithStruct
fluent#Post: can't convert to msgpack: {john smith} msgp: type "struct { Name string \"codec:\\\"name\\\"\" }" not supported
...
```

Until v0.5.1, ugorji/go/codec could accept values any types(= interface{}).
Now fluent.Entry.Record defined as interface{}, but msgp can't convert from struct to msgpack.

failure test case is below.

```go
func Test_EncodeData(t *testing.T) {
	s := struct {
		Name string `codec:"name"`
	}{
		"john smith",
	}
	var messages = []interface{}{
		1,
		"String",
		map[string]interface{}{
			"str":  "bar",
			"int":  1,
			"list": []int{1, 2, 3},
		},
		s,
	}
	for _, m := range messages {
		msg := &Message{Tag: "test", Time: time.Now().Unix(), Record: m}

		data, err := msg.MarshalMsg(nil)
		if err != nil {
			t.Error(err)
		}
		if data == nil {
			t.Error("MarshalMsg failed", msg)
		}
	}
}
```

**Comment by tagomoris** [comment]
Fluentd's records should be something like `map[string]interface{}`.
So I think that we should fix method signatures as `message map[string]interface{}`.

Any thoughts?

**Comment by fujiwara** [comment]
`map[string]interface{}` :+1:

For keeping backward compatibility, I hope bump up version when method signature will be changed.

* `interface{}` → http://gopkg.in/fluent/fluent-logger-golang.v0
* `map[string]interface{}` → http://gopkg.in/fluent/fluent-logger-golang.v1 ?

**Comment by tnir** [comment]
I encountered this issue during upgrading from v0.5.1 to v0.6.0 and made a workaround for it with [forking repo and set v0.5.1 as master branch](https://github.com/tnir/fluent-logger-golang).

Any update on this?

**Comment by tagomoris** [comment]
Should I remove `v0.6.0` tag and push `v1.0.0` with `map[string]interface{}` ?

**Comment by tnir** [comment]
Looks good. :+1:

**Comment by tagomoris** [comment]
I added some commits and tagged `v1.0.0`.
This version allows to feed both of `map[string]interface{}` and `struct`, and refer tags of both of `msg` and `codec` for encoding of structs.
On the other hand, `(* Fluent) Post` returns error of encoding values.

I believe that this issue is solved with that version, and @tnir 's forking repo is now useless.
@fujiwara @tnir Do you have any concern? Or can i close this issue?
Should i remove `v0.6.0` tags even now?

**Comment by tnir** [comment]
@tagomoris Thx.
http://gopkg.in/fluent/fluent-logger-golang.v0 still provides v0.6.0. I need http://gopkg.in/fluent/fluent-logger-golang.v0 points v0.5.1 or any version with v0.5.1-compatible interface, not v0.6.0.

If nobody started to use gopkg.in/fluent/fluent-logger-golang.v0, removing v0.6.0 tag is an option.

**Comment by tagomoris** [comment]
OK. I deleted `v0.6.0` tag.

**Comment by fujiwara** [comment]
:+1:

**Comment by tnir** [comment]
Thanks :+1:

**Comment by tagomoris** [comment]
Thank you to confirm!
