### ISSUE TITLE
Pending buffer could be written twice

### ISSUE THREAD

**Issue by nobu-k** [fluent/fluent-logger-golang#13]
In `Fluent.send`, `f.pending` is written as follows:

```
        f.mu.Lock()
        _, err = f.conn.Write(f.pending)
        f.mu.Unlock()
```

Let's say there're two goroutines A and B, and a problem can happen with the execution pattern below.
1. A acquires lock
2. B is blocked by the same lock
3. A writes `f.pending` and returns from `Fluent.send`
4. B writes `f.pending` before A flushes `f.pending` in `Fluent.PostRawData`

Because `f.pending`isn't flushed at the time B writes it and still have the same data which A just wrote, the same data can be written twice. To avoid this problem, `f.pending` must be flushed just after it's written without unlocking the mutex (i.e. in an atomic manner).

**Comment by tagomoris** [comment]
This is outdated and it should be resolved on the current code.
Let me close this ticket. Feel free to reopen if you still have this problem.
