### ISSUE TITLE
Support sending data as json

### ISSUE THREAD

**Issue by epelc** [fluent/fluent-logger-golang#23]
It would be nice if this library supported sending data as json instead of using msgpack. If your using this as a catch all error logger then a lot of things do not support being marshaled as msgpack. While practically everything works with the json marshaller.

**Comment by tagomoris** [comment]
Do you discussing only about marshaling of argument objects of logging methods, which supports to be serialized as JSON, but doesn't support to be serialized as MessagePack?
IMO, we have some options for that purpose:
* add support to marshal objects as json, and send it directly (Fluentd supports it)
* add feature to marshal objects as json at first, and then convert it into msgpack to send it

Both are acceptable for me. Pull requests are welcome :)

**Comment by tagomoris** [comment]
@epelc Does #27 solve your problem?

**Comment by epelc** [comment]
@tagomoris yes it should solve it.

@cosmo0920 Thanks for fixing this!

**Comment by tagomoris** [comment]
#27 now merged.
