### ISSUE TITLE
Release v1.0.1?

### ISSUE THREAD

**Issue by pcarrier** [fluent/fluent-logger-golang#26]
I'd like to add support for async connections in docker.

It is particularly useful there, as the fluent server could be in a container, and docker can't start the container until it's running... :)

Could you release a new version to that effect?

**Comment by tagomoris** [comment]
Sorry, I missed this issue.
IMO, recent change has functionality changes, so next version should be `v1.1.0`, instead of `v1.0.1`. Any thoughts?

**Comment by pcarrier** [comment]
Works for me :)

**Comment by tagomoris** [comment]
Okay.

**Comment by tagomoris** [comment]
I pushed commit and tag for `v1.1.0`.
97f4695b4d3f76180d24a8ba6d578e4e395ddc4c
