### ISSUE TITLE
it doesn't auto-reconnect when the connection is lost

### ISSUE THREAD

**Issue by nbaoping** [fluent/fluent-logger-golang#31]
From the code, if the connection to the fluentd server is lost (For example, the fluentd server is restarted), it seems the connection won't auto-reconnect and all the 'Post' methods don't return the 'send' error, so the program will never have the chance to detect the connection lost error. This may cause the logs lost. Please correct me if I am wrong.
```
func (f *Fluent) PostRawData(data []byte) {
    f.mu.Lock()
    f.pending = append(f.pending, data...)
    f.mu.Unlock()
    if err := f.send(); err != nil {
        f.close() //only close the connection but the error is not return, so how the program knows this error?
       if len(f.pending) > f.Config.BufferLimit {
            f.flushBuffer()
        }
    } else {
        f.flushBuffer()
    }
}
```

**Comment by tagomoris** [comment]
In `send`, this logger will try to reconnect if connection is already closed:
https://github.com/fluent/fluent-logger-golang/blob/master/fluent/fluent.go#L276

**Comment by nbaoping** [comment]
@tagomoris thanks for your reply. Yes, it will reconnect, but during the reconnecting, the logs will be lost and only errorlog is printed, the program will not be aware of the lost, is it true?

**Comment by tagomoris** [comment]
No, it's not true.
Arriving logs are appended to pending list at first before send, and after establishment of reconnection, it'll be sent to destination.
https://github.com/fluent/fluent-logger-golang/blob/master/fluent/fluent.go#L170
