### ISSUE TITLE
Connection pool support

### ISSUE THREAD

**Issue by hnlq715** [fluent/fluent-logger-golang#5]
Any plan for connection pool support? Or maybe I should try to implement this myself...

**Comment by najeira** [comment]
This plugin keep a connection while sending.
I think connection pooling is not so effective.

**Comment by hnlq715** [comment]
@najeira Thanks for your reply.
OK, it's long time since I commented this, and I just gave up to implement this feature...
Because I had found a bigger mistake in this plugin...Or maybe fluentd's communication design.

When we connect fluentd through this plugin, there's no way to know if fluentd has closed this connection. So we just keep sending to a meaningless connection and lost data, while fluentd closes it.

**Comment by najeira** [comment]
@hnlq715 I agree. `PostRawData` does not return error, it behavior is not good.

**Comment by hnlq715** [comment]
@najeira yeah, so I've switched to `logstash` :smile:
