### ISSUE TITLE
Buffer lock can block client (i.e, dockerd)

### ISSUE THREAD

**Issue by stefano-pogliani** [fluent/fluent-logger-golang#54]
Hello,

We have experienced a couple of blocked web server containers in our production infrastructure caused by fluentd being overloaded.

I suspect this is caused by the attempt of [`send`](https://github.com/fluent/fluent-logger-golang/blob/a8dfe4adfeaf7b985acb486f6b060ff2f6a17e91/fluent/fluent.go#L316) to flush the entire buffer and [keeping a hold on the buffer lock](https://github.com/fluent/fluent-logger-golang/blob/a8dfe4adfeaf7b985acb486f6b060ff2f6a17e91/fluent/fluent.go#L312) while doing so.
If the fluend server is slow for any reason the `send` method will slowly loop until the buffer is empty.
In the meantime, any attempt to log will block at the [`appendBuffer`](https://github.com/fluent/fluent-logger-golang/blob/a8dfe4adfeaf7b985acb486f6b060ff2f6a17e91/fluent/fluent.go#L241) level because `send` still has the lock.

While looking for known issues/prs I found https://github.com/fluent/fluent-logger-golang/issues/33 and the implementing PR from @alexlry https://github.com/fluent/fluent-logger-golang/pull/52 which would remove the lock altogether.

It would be great if that PR could be reviewed and merged in so that docker containers would not longer block while trying to write to stdout but rather fail with full buffers.

I have also built a Gist detailing how to reproduce this issue with docker-compose and tc: https://gist.github.com/stefano-pogliani/463af63c040d1bd3740fb46255d2768a

**Comment by thaJeztah** [comment]
@tagomoris @alexlry should this one be closed (resolved by https://github.com/fluent/fluent-logger-golang/pull/56)?
