### ISSUE TITLE
CI is outdated

### ISSUE THREAD

**Issue by szamuboy** [fluent/fluent-logger-golang#60]
CI tries to compile with golang v1.3, v.1.4, v.1.5 and tip.

The command `go get github.com/tinylib/msgp` fails with the old go versions. I guess the `tinylib/msgp` does not support the old go versions anymore.

For reference, see https://travis-ci.org/fluent/fluent-logger-golang/builds/463739411

**Comment by tagomoris** [comment]
Can you create a pull-req to update these dependencies or golang versions?

**Comment by szamuboy** [comment]
Fixed in 1.4.0
