### ISSUE TITLE
Post Method is not Throwing error when the machine is not reachable

### ISSUE THREAD

**Issue by Manikandan-Raj** [fluent/fluent-logger-golang#65]
logger, err := fluent.New(fluent.Config{FluentPort: config.Aggregatorport, FluentHost: config.Aggregatorip})

At this time, i am getting logger instance.
Then reading file content which i want send to my log aggregator.
Something like this:
for value := range result{
error := logger.Post(tag, value)
if error != nil {
// Assumes that machine is not reachable, so writing back to the file.
}
}

Network connection is getting break while i am inside for-loop, but that error instance is still nil.
What really Post method is doing here????

**Comment by tagomoris** [comment]
> What really Post method is doing here????
You can read the code anytime. https://github.com/fluent/fluent-logger-golang/blob/master/fluent/fluent.go

We are always welcome to bug reports, but please report bugs with the exact code (not pseudo code) and the steps how to reproduce it.

**Comment by Manikandan-Raj** [comment]
package main

import (
"fmt"
"encoding/json"
syslog_fmt "gopkg.in/mcuadros/go-syslog.v2/format"
"github.com/fluent/fluent-logger-golang/fluent"
"io/ioutil"
"io"
"os"
syslog "gopkg.in/mcuadros/go-syslog.v2"
"flag"
)

var (
fileObject *os.File
bufferfileSize = flag.Int64("bytesize", 0, "Track the file size")
)


func forwardToAggregator(logParts syslog_fmt.LogParts){
  tag := "datacollector"
  data := make(map[string]interface{})
  data["content"] = logParts["content"].(string)
  data["hostname"] = logParts["hostname"].(string)
  data["severity"] = logParts["severity"].(int)
  data["facility"] = logParts["facility"].(int)
  data["priority"] = logParts["priority"].(int)

  fileObject, _ = os.OpenFile("test.json", os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0666)
  logger, err := fluent.New(fluent.Config{FluentPort: X.X.X.X, FluentHost: XXXX})
  if err != nil {
      # Machine is not reachable/ Network failure, so saving logs to file
      file, _ := json.Marshal(data)
      route_messages_tofile(string(file))
  } else {
  sending_to_aggregator(logger, data, tag)
  fi,_ := fileObject.Stat()
  *bufferfileSize = fi.Size()
  if *bufferfileSize != 0 {
	     send_logs_fromfile(logger, tag)
  }
  }

  defer logger.Close()
}



func route_messages_tofile(content string){
	n, err := io.WriteString(fileObject, string(content)+",")
	if err != nil {
			fmt.Println(n, err)
	}
}


func sending_to_aggregator(logger *fluent.Fluent, data map[string]interface{}, tag string){
	fmt.Println("Posting logs to aggregator")
	error := logger.Post(tag, data)
  fmt.Println("Error", error)
	if error != nil {
	file, _ := json.Marshal(data)
	route_messages_tofile(string(file))
	}
}

func send_logs_fromfile(logger *fluent.Fluent, tag string){
  fmt.Println("Aggregator came back to normal state")
  fmt.Println("Going to sent the logs from File content")
  fmt.Println("************************************")
	content, _ := ioutil.ReadFile("/home/mani/logmonitor/test.json")
	err := os.Truncate("/home/mani/logmonitor/test.json", 0)
	if err != nil {
			panic(err)
	}
  
  file_content :=  string(content)
  processed_content := file_content[:len(file_content)-1]
  processed_content = "["+string(processed_content)+"]"

  var result []map[string]interface{}
  fmt.Println("Content of the file", processed_content)
  fmt.Println("*************************************")
  json.Unmarshal([]byte(processed_content), &result)

  for value := range result{
         forward_to_aggregator(logger, result[value], tag)
         fmt.Println("Value", result[value])
   }
}

func main() {
channel := make(syslog.LogPartsChannel)
handler := syslog.NewChannelHandler(channel)
server := syslog.NewServer()
server.SetFormat(syslog.Automatic)
server.SetHandler(handler)

server.ListenTCP("0.0.0.0:514")
server.Boot()

go func(channel syslog.LogPartsChannel) {
    for logParts := range channel {
	     forwardToAggregator(logParts)
}

}(channel)
server.Wait()
}
