### ISSUE TITLE
Are idle timeouts/ keepalives being observed?

### ISSUE THREAD

**Issue by eddgrant** [fluent/fluent-logger-golang#70]
Hi folks,

I'm running FluentBit behind an AWS Network Load Balancer (running in TCP mode) in conjunction with the [fluentd Docker log driver](https://docs.docker.com/config/containers/logging/fluentd/) and am seeing occasional dropping of logs. On investigation this seems to occur only when there are sudden large increases in traffic from previously low (or nil) levels. When this happens I observe that the NLB initially returns reset packets to the clients (in this case the fluentd log driver I believe) before beginning to receive new connections.

As per the [AWS NLB docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html) I'm aware that NLBs have a hardcoded idle timeout value of 350 seconds. The idle timeout value can be reset through the sending of keepalive packets.

This made me wonder if the fluentd log driver either sends keepalives, or checks for reset packets in its connections? I don't know golang so may have missed it when looking at the code here but couldn't see anything which would suggest either of these are in place.

Most grateful for your thoughts.

Cheers,

Edd

Environment:
Docker: 19.03.2, build 6a30dfc
FluentBit: Have tried both 1.2.2 and 1.3.0, both exhibit the same behaviour.

**Comment by tagomoris** [comment]
fluent-logger-golang (Fluentd log driver for docker) doesn't send keepalive packets, nor check reset packets.
I'm happy to merge the changes to support this use-case.

**Comment by eddgrant** [comment]
Hi @tagomoris , thanks for getting back to me.

Unfortunately I'm not currently in a position to be able to contribute to such a change. My #golang knowledge just isn't up to the task. If this changes I will happily come back to you though.

While I have your attention, could I ask one more question? Does fluent-logger-golang support TLS connections? I have a requirement that my entire log forwarding journey is done securely, which in this case would mean using TLS between fluent-logger-golang and the load balancer.

Many thanks,

Edd

**Comment by tagomoris** [comment]
Neither.

I've added this commit: c032cb0ca701135e3541cee1ef2e641b8fa4df2b

**Comment by eddgrant** [comment]
Understood. Thanks for the clarification (and the doc updates!) :+1:
