### ISSUE TITLE
Can't convert … not supported at Record

### ISSUE THREAD

**Issue by tskardal** [fluent/fluent-logger-golang#75]
I experienced this while using logrus_fluent (which use this library).

I have a type alias defined as 

```
type Mode = string
```

When I try to log a message with `.WithFields(logrus.Fields{})` and use this type, I get the following error:

```
Failed to fire hook: fluent#EncodeAndPostData: can't convert 
'map[string]interface {}{"":"Starting process", "args":[]interface {}{"10000"}, "cmd":"sleep", "level":"info", "mode":"launcher"}' 
to msgpack:msgp: type "config.Mode" not supported at Record
```
(note: I've added some newlines to the message for readability)

The workaround in this case is to just convert the Mode value back to string:

```
log.WithFields(logrus.Fields{
		"mode": string(config.Mode),
})
```

**Comment by tagomoris** [comment]
Acceptable data types are described [here](https://github.com/fluent/fluent-logger-golang#example} about this library, and libraries which use this should follow the order. It's not the issue of this library.
