### ISSUE TITLE
Work with fluent-bit?

### ISSUE THREAD

**Issue by clarktlaugh** [fluent/fluent-logger-golang#76]
I'm having a problem getting this to work with fluent-bit.  Is it expected to?

I have verified that fluent-bit is running and have tried using using both **forward** and **tcp** input plugins, but neither work.  I keep getting errors like:

```
fluent#write: failed to reconnect, max retry 0
```

If I use `nc` and write some simple JSON to the ip/port that fluent-bit is listening on (the **tcp** input), it is logged by fluent-bit.

**Comment by tagomoris** [comment]
This logger is to send events using Fluentd forward protocol. Use `forward` input plugin of fluent-bit.

**Comment by clarktlaugh** [comment]
Is there a specific version requirement?  I have tried using the forward
input plugin and can’t get the client connect.
