### ISSUE TITLE
How about to move this repository under fluent organization?

### ISSUE THREAD

**Issue by tagomoris** [fluent/fluent-logger-golang#8]
Hi,

This module is now depended by many software written in golang, but there seems be not so many maintainers against its importance.

So, I will propose to move this repository under fluent organization. I think that i can use some of my time to maintain this library. In fact, now I want to add some methods for logging driver of docker for fluentd.

@t-k How do you think about this proposal?

**Comment by t-k** [comment]
Hi @tagomoris ,

Thanks for your proposal. I would like to follow it.
So, is it okay to transfer this repo to your organization(https://github.com/fluent)? Please tell me if there is a procedure required.

**Comment by tagomoris** [comment]
@t-k I've just invited you to "Team Golang" in fluent organization. Please confirm it.
And then, you may execute "transfer" from Setting of this repository, to fluent organization.

**Comment by t-k** [comment]
Done! Thanks.

**Comment by tagomoris** [comment]
Great! Thank you so much.
