### ISSUE TITLE
How to forward output plugin records

### ISSUE THREAD

**Issue by ericmillin** [fluent/fluent-logger-golang#94]
I have written a Go output plugin for fluentbit. The records the plugin receives are in msgpack format. The plugin forwards the unprocessed records to an endpoint. The endpoint will use `fluent-logger-golang` to post the records to another fluentbit instance.

It appears I would have to decode the records, unmarshal them, then post them. That obviously isn't very efficient. The ideal method wouldn't involve any re-encoding or marshaling. E.g.,
```
func (f *Fluent) PostRawRecords(tag string, records []bytes)
```
where `records` is the same byte blob as passed to the output plugin.

Is something like that possible? If it's possible, but not implemented, would you accept a PR?

**Comment by tagomoris** [comment]
At first, `PostRawRecords` is a deprecated function and will be removed in the future.
fluent-logger-golang is to send events to fluentd/fluentbit, not forward messages already encoded. It's out of this project's scope, and I'll not merge such changes because it'll increase the maintenance cost.

**Comment by ericmillin** [comment]
I would maintain it because the other option is to fork, which is an epic PITA. However, I understand your position. Thanks for the response.

**Comment by ericmillin** [comment]
closing
